from django.core.management.base import BaseCommand
from Authentication.models import Provinces, Cities

class Command(BaseCommand):
    help = 'Create objects'
    def handle(self, *args, **kwargs):
        obj1 = Provinces.objects.all().count()
        if (obj1 > 0):
            self.stdout.write(self.style.SUCCESS('creation failed due to existence of at least one province in MayorRegistry_provinces'))
            return
        obj = Provinces(Name="آذربایجان شرقی")
        obj.save()
        obj2 = Cities(Name="کشکسرای", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سهند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دوزدوزان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تیمورلو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صوفیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سردرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هادیشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هشترود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرنق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ترکمانچای", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ورزقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تسوج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زنوز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایلخچی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شرفخانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهربان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مبارک شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تیکمه داش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باسمنج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیه رود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خمارلو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خواجه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بناب مرند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قره آغاج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="وایقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مراغه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ممقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خامنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خسروشاه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لیلان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نظرکهریزی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بخشایش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آقکند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوان قلعه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلیبر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مرند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسکو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شندآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شریبان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گوگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بستان آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تبریز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جلفا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اچاچی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هریس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="یامچی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خاروانا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوزه کنان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خداجو(خراجو)", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آذرشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شبستر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سراب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ملکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بناب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هوراند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلوانق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ترک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عجب شیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبش احمد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('1'))

        obj = Provinces(Name="آذربایجان غربی")
        obj.save()
        obj2 = Cities(Name="تازه شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نالوس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایواوغلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاهین دژ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گردکشانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باروق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیلوانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بازرگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نازک علیا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ربط", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تکاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دیزج دیز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیمینه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوشین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میاندوآب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مرگنلر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سلماس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آواجیق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قطور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمودآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خوی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نقده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خلیفان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پلدشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اشنویه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بوکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پیرانشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چهاربرج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قوشچی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شوط", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماکو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیه چشمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سردشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کشاورز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فیرورق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمدیار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارومیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهاباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قره ضیاالدین", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('2'))

        obj = Provinces(Name="اردبیل")
        obj.save()
        obj2 = Cities(Name="پارس آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فخرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اردبیل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسلام آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تازه کندانگوت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مشگین شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جعفر آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نمین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اصلاندوز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مرادلو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خلخال", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوراییم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گیوی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گرمی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لاهرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هشتجین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عنبران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تازه کند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قصابه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رضی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرعین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیله سوار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبی بیگلو", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('3'))

        obj = Provinces(Name="اصفهان")
        obj.save()
        obj2 = Cities(Name="گزبرخوار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زیار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرین شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلشن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پیربکران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خالدآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سجزی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گوگد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تیران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ونک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زواره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کاشان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ابوزید آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اصغر آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بافران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهرضا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مجلسی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هرند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فولادشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کمشچه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلیشادوسودرجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لای بید", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قهجاورستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چرمهین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رزوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فریدونشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="طرق رود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نصر آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="برزک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سفید شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سمیرم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلدشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اردستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوشان قالی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بویین و میاندشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کرکوند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درچه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="انارک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دولت آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایمانشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گرگاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حسن آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سده لنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حبیب آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهاران شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تودشک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رضوانشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="داران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="علویجه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیک آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مشکات", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آران و بیدگل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خوانسار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نجف آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="منظریه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فرخی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دیزیچه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اژیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زاینده رود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خورزوق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قهدریجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاهین شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهارستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چمگردان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهاقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="برف انبار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بادرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهپایه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلپایگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عسگران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حنا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کهریزسنگ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهاباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کامو و چوگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="افوس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زیبا شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوشک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نایین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زازران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مبارکه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ورزنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ورنامخواست", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاپورآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فلاورجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="وزوان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اصفهان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باغ بهادران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چادگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دامنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نطنز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمد آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیاسر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوش آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوزدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قمصر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جندق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="طالخونچه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خمینی شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باغشاد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دستگرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ابریشم", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('4'))


        obj = Provinces(Name="البرز")
        obj.save()
        obj2 = Cities(Name="چهارباغ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آسارا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کرج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="طالقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هشتگرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمدشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مشکین دشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نظر آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماهدشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اشتهارد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهسار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گرمدره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تنکمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلسار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کمال شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فردیس", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('5'))

        obj = Provinces(Name="ایلام")
        obj.save()
        obj2 = Cities(Name="آبدانان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شباب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="موسیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بدره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایلام", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایوان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آسمان آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پهله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سراب باغ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بلاوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دره شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارکواز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مورموری", Province=obj)
        obj2.save()
        obj2 = Cities(Name="توحید", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهلران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لومار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چوار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صالح اباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرابله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماژین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دلگشا", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('6'))

        obj = Provinces(Name="بوشهر")
        obj.save()
        obj2 = Cities(Name="ریز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="برازجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندرریگ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اهرم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دوراهک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خورموج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نخل تقی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر دیلم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="وحدتیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بنک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چغادک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر دیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کاکی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دالکی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر گناوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خارک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شنبه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بوشکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="انارستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شبانکاره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیراف", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دلوار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بردستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بادوله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عسلویه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تنگ ارم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="امام حسن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سعد آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر کنگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بوشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بردخون", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آب پخش", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('7'))

        obj = Provinces(Name="تهران")
        obj.save()
        obj2 = Cities(Name="شاهدشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پیشوا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوادآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارجمند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ری", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نصیرشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رودهن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اندیشه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نسیم شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صباشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ملارد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شمشک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پاکدشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باقر شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="احمد آباد مستوفی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کیلان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قرچک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فردوسیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ورامین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فیروزکوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فشم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پرند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبعلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چهاردانگه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تهران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بومهن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="وحیدیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صفادشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لواسان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فرون آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کهریزک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رباط کریم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبسرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باغستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صالحیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهریار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قدس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تجریش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شریف آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حسن آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسلامشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دماوند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پردیس", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('8'))

        obj = Provinces(Name="چهارمحال و بختیاری")
        obj.save()
        obj2 = Cities(Name="وردنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گوجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گهرو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سورشجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرخون", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهرکرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="منج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بروجن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پردنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سامان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فرخ شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صمصامی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="طاقانک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کاج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نقنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لردگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باباحیدر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دستنا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سودجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بازفت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هفشجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سردشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فرادبنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چلیچه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فارسان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شلمزار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نافچ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دشتک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بلداجی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آلونی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گندمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جونقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ناغان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هارونی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چلگرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اردل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سفیددشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مال خلیفه", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('9'))

        obj = Provinces(Name="خراسان جنوبی")
        obj.save()
        obj2 = Cities(Name="اسلامیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شوسف", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قاین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عشق آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="طبس مسینا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارسک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آیسک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیمبلوک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دیهوک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سربیشه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمدشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیرجند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فردوس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نهبندان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسفدن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گزیک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حاجی آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سه قلعه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آرین شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خوسف", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قهستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بشرویه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرایان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خضری دشت بیاض", Province=obj)
        obj2.save()
        obj2 = Cities(Name="طبس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسدیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زهان", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('10'))

        obj = Provinces(Name="خراسان رضوی")
        obj.save()
        obj2 = Cities(Name="بار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیل شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جنگل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رباط سنگ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سلطان آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فریمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گناباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کاریز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="همت آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سلامی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باجگیران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بجستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چناران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درگز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلات", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چکنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نصرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بردسکن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مشهد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کدکن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نقاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قلندرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کاشمر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاندیز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نشتیفان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ششتمد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شادمهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عشق آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چاپشلو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رشتخوار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قدمگاه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صالح آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="داورزن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فرهادگرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کاخک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مشهدریزه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جغتای", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مزدآوند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قوچان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="یونسی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سنگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوخندان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کندر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیشابور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="احمدآبادصولت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رضویه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تربت حیدریه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باخرز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سفیدسنگ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیدخت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تایباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فیروزه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قاسم آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سبزوار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فیض آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلمکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لطف آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهرزو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خرو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تربت جام", Province=obj)
        obj2.save()
        obj2 = Cities(Name="انابد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ملک آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بایک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دولت آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرخس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ریوش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="طرقبه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خواف", Province=obj)
        obj2.save()
        obj2 = Cities(Name="روداب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خلیل آباد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('11'))

        obj = Provinces(Name="خراسان شمالی")
        obj.save()
        obj2 = Cities(Name="چناران شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="راز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پیش قلعه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قوشخانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شوقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسفراین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گرمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قاضی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شیروان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حصارگرمخان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آشخانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تیتکانلو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جاجرم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بجنورد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آوا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زیارت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سنخواست", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صفی آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فاروج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لوجلی", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('12'))

        obj = Provinces(Name="خوزستان")
        obj.save()
        obj2 = Cities(Name="هفتگل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیدروبه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاوور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حمزه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گتوند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شرافت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="منصوریه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زهره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رامهرمز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر امام خمینی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوت عبداله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میداود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چغامیش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ملاثانی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چم گلک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شمس آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبژدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چویبده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مسجدسلیمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مقاومت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ترکالکی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دارخوین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سردشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لالی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوت سیدنعیم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حمیدیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهدز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قلعه تل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میانرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رفیع", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اندیمشک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="الوان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سالند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صالح شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اروند کنار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرداران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تشان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رامشیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شادگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندرماهشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جایزان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ویس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اهواز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فتح المبین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهر امام", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قلعه خواجه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حسینیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلگیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مینوشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سماله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شوشتر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهبهان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هندیجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ابوحمیظه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آغاجاری", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایذه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صیدون", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیاه منصور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هویزه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آزادی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شوش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دزفول", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جنت مکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبادان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گوریه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خرمشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مشراگه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خنافره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چمران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="امیدیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سوسنگرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شیبان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="الهایی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باغ ملک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صفی آباد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('13'))

        obj = Provinces(Name="زنجان")
        obj.save()
        obj2 = Cities(Name="سجاس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرین رود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آب بر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارمغانخانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کرسف", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هیدج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سلطانیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خرمدره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیک پی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قیدار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ابهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دندی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حلب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوربهار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گرماب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چورزق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سهرورد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صایین قلعه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماه نشان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرین آباد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('14'))

        obj = Provinces(Name="سمنان")
        obj.save()
        obj2 = Cities(Name="ایوانکی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مجن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دامغان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرخه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهدی شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاهرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سمنان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کهن آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گرمسار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلاته خیج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دیباج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درجزین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رودیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بسطام", Province=obj)
        obj2.save()
        obj2 = Cities(Name="امیریه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میامی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهمیرزاد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیارجمند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلاته", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آرادان", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('15'))

        obj = Provinces(Name="سیستان و بلوچستان")
        obj.save()
        obj2 = Cities(Name="محمدی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهرک علی اکبر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بنجار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلمورتی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نگور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="راسک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بنت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قصرقند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جالق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هیدوچ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوک آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زهک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بمپور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پیشین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمدآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زاهدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زابلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چاه بهار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بزمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسپکه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فنوج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سراوان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ادیمی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زابل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دوست محمد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایرانشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرباز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیرکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میرجاوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نصرت آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سوران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خاش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کنارک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیک شهر", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('16'))

        obj = Provinces(Name="فارس")
        obj.save()
        obj2 = Cities(Name="کازرون", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کارزین (فتح آباد)", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فدامی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خومه زار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سلطان شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فیروزآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دبیران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باب انار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رامجرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سروستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قره بلاغ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارسنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دژکرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیرم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهرم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شیراز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایزدخواست", Province=obj)
        obj2.save()
        obj2 = Cities(Name="علاومرودشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اوز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="وراوی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیضا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نی ریز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کنار تخته", Province=obj)
        obj2.save()
        obj2 = Cities(Name="امام شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جهرم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بابامنیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گراش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فسا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهرپیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حسن آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کام فیروز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خنج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خانه زنیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="استهبان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بوانات", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لطیفی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فراشبند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صغاد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اشکنان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قایمیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گله دار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دوبرجی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آباده طشک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خرامه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میمند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="افزر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دوزه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوپن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زاهدشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قادرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بنارویه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سعادت شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهرصدرا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سورمق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حسامی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جویم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خوزی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اردکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قطرویه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نودان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مبارک آباددیز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="داراب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نورآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوبندگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حاجی آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خاوران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ششده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مزایجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوجین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لپویی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهمن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اهل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جنت شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مشکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بالاده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قطب آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خانیمن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مصیری", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میانشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صفاشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اقلید", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عمادده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مادرسلیمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="داریان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رونیز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کره ای", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هماشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آباده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لامرد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('17'))

        obj = Provinces(Name="قزوین")
        obj.save()
        obj2 = Cities(Name="سگزآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیدستان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رازمیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خرمدشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبگرم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شال", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شریفیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اقبالیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نرجه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارداق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="الوند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خاکعلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیردان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ضیادآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بویین زهرا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمدیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمودآبادنمونه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="معلم کلایه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسفرورین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آوج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دانسفهان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آبیک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قزوین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تاکستان", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('18'))

        obj = Provinces(Name="قم")
        obj.save()
        obj2 = Cities(Name="کهک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سلفچگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جعفریه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قنوات", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دستجرد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('19'))

        obj = Provinces(Name="کردستان")
        obj.save()
        obj2 = Cities(Name="قروه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="توپ آغاج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سروآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بویین سفلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرینه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دلبران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سنندج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="یاسوکند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="موچش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مریوان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سریش آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صاحب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهگلان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بابارشانی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دیواندره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="برده رشه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شویشه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیجار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اورامان تخت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کانی سور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کانی دینار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دزج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سقز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بلبلان آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پیرتاج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کامیاران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آرمرده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چناره", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('20'))

        obj = Provinces(Name="کرمان")
        obj.save()
        obj2 = Cities(Name="کهنوج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بلوک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پاریز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گنبکی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زنگی آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خانوک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کیانشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوپار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عنبرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوزم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نظام شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لاله زار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کشکوییه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زیدآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هنزا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چترود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جبالباز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیرجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رودبار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کرمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بافت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صفاییه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="منوجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اندوهجرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هجدک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خورسند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="امین شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بردسیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رفسنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هماشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمدآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اختیارآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بروات", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ریحان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهبنان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماهان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دوساری", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فاریاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلزار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهرمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بلورد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فهرج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کاطم آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جیرفت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نجف شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قلعه گنج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باغین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بزنجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نودژ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گلباف", Province=obj)
        obj2.save()
        obj2 = Cities(Name="راور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خاتون آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نرماشیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دشتکار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مس سرچشمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خواجه شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رابر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="راین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درب بهشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="یزدان شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زهکلوت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مخی آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مردهک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهداد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارزوییه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نگار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهر بابک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="انار", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('21'))

        obj = Provinces(Name="کرمانشاه")
        obj.save()
        obj2 = Cities(Name="سنقز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاهو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بانوره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تازه آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هلشی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوانرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قصرشیرین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوسود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کرند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوزران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیستون", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حمیل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گیلانغرب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سطر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="روانسر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پاوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ازگله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کرمانشاه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میان راهان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کنگاور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرپل ذهاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ریجاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باینگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هرسین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسلام آبادغرب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرمست", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سومار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نودشه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="'گهواره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رباط", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صحنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گودین", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('22'))

        obj = Provinces(Name="کهگیلویه و بویراحمد")
        obj.save()
        obj2 = Cities(Name="'گراب سفلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لنده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سی سخت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهدشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="یاسوج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرفاریاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دوگنبدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چیتاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لیکک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دیشموک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مادوان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="باشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پاتاوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قلعه رییسی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مارگون", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چرام", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سوق", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('23'))

        obj = Provinces(Name="گلستان")
        obj.save()
        obj2 = Cities(Name="سیمین شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مزرعه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رامیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فراغی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گنبد کاووس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کردکوی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مراوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر ترکمن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نگین شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آق قلا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرخنکلاته", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گالیکش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سنگدوین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دلند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر گز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوده خاندوز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مینودشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گرگان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گمیش تپه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="علی آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خان ببین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلاکه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اینچه برون", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فاضل آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تاتارعلیا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوکنده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آزادشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="انبارآلوم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جلین", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('24'))

        obj = Provinces(Name="گیلان")
        obj.save()
        obj2 = Cities(Name="منجیل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شلمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خشکبیجار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماکلوان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سنگر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مرجقل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لیسار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رضوانشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رحیم آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لوندویل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="احمدسرگوراب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لوشان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اطاقور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لست نشا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فومن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چوبر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بازار جمعه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلاچای", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندر انزلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="املش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رستم آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لاهیجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="توتکابن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لنگرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوچصفهان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صومعه سرا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسالم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دیلمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رودسر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کیاشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شفت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رودبار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کومله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماسوله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خمام", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ماسال", Province=obj)
        obj2.save()
        obj2 = Cities(Name="واجارگاه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هشتپر(تالش)", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پره سر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بره سر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آستارا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رودبنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جیرنده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چاف و چمخاله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لولمان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گوراب و زرمیخ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حویق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیاهکل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چابکسر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آستانه اشرفیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رانکوه", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('25'))

        obj = Provinces(Name="لرستان")
        obj.save()
        obj2 = Cities(Name="چالانچولان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بیران شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ویسیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شول آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پلدختر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهدشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هفت چشمه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بروجرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="الشتر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مومن آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دورود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زاغه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چقابل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="الیگودرز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="معمولان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهنانی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نورآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سپیددشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سراب دوره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ازنا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گراب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خرم آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اشترینان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فیروزآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درب کنبد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('26'))

        obj = Provinces(Name="مازندران")
        obj.save()
        obj2 = Cities(Name="گلوگاه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پل سفید", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دابودشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چالوس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کیاسر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهنمیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تنکابن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلاردشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ایزدشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گتاب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سلمان شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ارطه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="امیرکلا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهی خیل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پایین لاهور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گزنگ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محمودآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رامسر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خلیل شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کیاکلا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مرزینکلا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فریدون کنار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زیرآب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="امامزاده عبدالله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هچیرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فریم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هادی شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نشتارود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پول", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهشهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کلارآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بلده", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بابل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جویبار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آلاشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آمل", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نکا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کتالم و سادات شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بابلسر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شیرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شیرگاه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رویان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زرگرمحله", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عباس آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قایم شهر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خوش رودپی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مرزن آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="یاری", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رینه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرخرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خرم آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کجور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رستمکلا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سورک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چمستان", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('27'))

        obj = Provinces(Name="مرکزی")
        obj.save()
        obj2 = Cities(Name="آستانه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خنجین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نراق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کمیجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آشتیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رازقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهاجران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="غرق آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خنداب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قورچی باشی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خشکرود", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ساروق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="محلات", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شازند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ساوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میلاجرد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تفرش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زاویه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اراک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="توره", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نوبران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فرمهین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دلیجان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پرندک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کارچان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیمور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هندودر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جاورسیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خمین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مامونیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="داودآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شهباز", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('28'))

        obj = Provinces(Name="هرمزگان")
        obj.save()
        obj2 = Cities(Name="بیکا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تیرور", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گروک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قشم", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوشنار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کیش", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرگز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندرعباس", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زیارتعلی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سندرک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کوهستک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لمزان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رویدر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قلعه قاضی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فارغان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ابوموسی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هشتبندی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سردشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="درگهان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="پارسیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کنگ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جناح", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تازیان پایین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دهبارز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میناب", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سیریک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سوزا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خمیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="چارک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حاجی آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندرجاسک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گوهران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هرمز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دشتی", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بندرلنگه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بستک", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تخت", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('29'))

        obj = Provinces(Name="همدان")
        obj.save()
        obj2 = Cities(Name="زنگنه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="دمق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سرکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="آجین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جورقان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="برزول", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فامنین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="سامن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فرسفج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شیرین سو", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مریانج", Province=obj)
        obj2.save()
        obj2 = Cities(Name="فیروزان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قروه درجزین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ازندریان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="لالجین", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گل تپه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="گیان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ملایر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="صالح آباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تویسرکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اسدآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="همدان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نهاوند", Province=obj)
        obj2.save()
        obj2 = Cities(Name="رزن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="جوکار", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهاجران", Province=obj)
        obj2.save()
        obj2 = Cities(Name="کبودرآهنگ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="قهاوند", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('30'))

        obj = Provinces(Name="یزد")
        obj.save()
        obj2 = Cities(Name="مروست", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهردشت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="حمیدیا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="تفت", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اشکذر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ندوشن", Province=obj)
        obj2.save()
        obj2 = Cities(Name="یزد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="عقدا", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بهاباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="ابرکوه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="زارچ", Province=obj)
        obj2.save()
        obj2 = Cities(Name="نیر", Province=obj)
        obj2.save()
        obj2 = Cities(Name="اردکان", Province=obj)
        obj2.save()
        obj2 = Cities(Name="هرات", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بفروییه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="شاهدیه", Province=obj)
        obj2.save()
        obj2 = Cities(Name="بافق", Province=obj)
        obj2.save()
        obj2 = Cities(Name="خضرآباد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="میبد", Province=obj)
        obj2.save()
        obj2 = Cities(Name="مهریز", Province=obj)
        obj2.save()
        obj2 = Cities(Name="احمدآباد", Province=obj)
        obj2.save()
        self.stdout.write(self.style.SUCCESS('31'))

        self.stdout.write(self.style.SUCCESS('Successfully created all Cities and Provinces'))