name: Build and Deploy CivilRadar Api

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_call:

jobs:
 build-and-deploy:
   name: Build and Deploy
   runs-on: ubuntu-24.04
   container:
    image: ubuntu:noble
   steps:
   - name: Install git
     run: bash -c "apt update -y && apt upgrade -y && apt install git -y"
   - name: Checking out from source control
     uses: actions/checkout@v3
   - name: Installing dependencies
     run: ./tools/install_dependencies.bash
   - name: Creating venv
     run: bash -c "python3 -m venv .venv && source .venv/bin/activate && pip install -r CityHorizon/requirements.txt"
   - name: Require test and run time requiremenst
     run: ./tools/require_runtime_dependencies.bash
   - name: Run Tests
     run: bash -c "git config --global --add safe.directory $(pwd) && git fetch origin && git checkout 5b62af07ac227f2558b7f24d3eec10c300cf1a83 && source .venv/bin/activate && cd CityHorizon && ./manage.py makemigrations && ./manage.py migrate && ./manage.py test Authentication.tests --exclude-tag=unstable --parallel"
